sentence=input("enter a sentence:")
cleaned=sentence.strip()
normalised=cleaned.lower().replace("."," ")
words=normalised.split()
slug="-".join(words)
uppercase=normalised.upper()
position=normalised.find("python")

print("Cleaned:",cleaned)
print("Normalised:",normalised)
print("Words:",words)
print("Slug:",slug)
print("Uppercase:",uppercase)
print("Position of python:",position)